### ISSUE TITLE
Peer to Peer review week 3 - Updates on Portfolio

### ISSUE THREAD

**Issue by enmanuelbayen** [mpa-mxiang/profolio2#10]
I kindly suggest you use a different unit of measure for your texts. 

I kindly suggest you align your page to achieve better visual aesthetics.

**Comment by mrcbq** [comment]
Hello, @mpa-mxiang  good job with you. To improve your code I think that you can review the following points:
1 - Tha navbar is not accessible through navigation with the keyboard. Maybe you can review the w3c guide about it https://www.w3.org/WAI/test-evaluate/preliminary/#interaction
2- Maybe you are losing something important as a requirements project, the cards must be changed when are hover it. It's possible that you check again the Figma template and try to implement it, to improve your portfolio webpage, stick to the Figma template and practice one good characteristic with CSS.

**Comment by mpa-mxiang** [comment]
Fixed above issues ✅
