### ISSUE TITLE
JavaScript files and repeating declarations of variables

### ISSUE THREAD

**Issue by romans-adi** [mpa-mxiang/profolio2#16]
:hammer: Hi! I like your project, but I must point out a few essential things. :wrench: 

- ### 4 JavaScript files 

As far as most of your code is related to DOM manipulations and is client-side, there's no need to create a new file for each function. Generally, loading more files incurs more overhead in HTTP.

Also, you linked storage.js file twice [here](https://github.com/mpa-mxiang/profolio2/blob/data-storage/index.html#L217) and [here](https://github.com/mpa-mxiang/profolio2/blob/data-storage/index.html#L221) in your HTML document.

    <script src="storage.js"></script>
    <script src="menu.js"></script>
    
    <script src="popup.js"></script>
    <script src="storage.js"></script>

- ### Repeating declaration of variables

The previous issues created another one. While you declaring in one file, after linking each to HTML document it calls the same variables (because of scope) and you receive such errors:
      
    caught SyntaxError: Identifier 'emailInput' has already been declared (at storage.js:1:1)

You must declare a variable with the same name only once in your code. If you want to rewrite your variable later, you can use **let** instead of **const**.

-------------------------------------------------------------------------------------------------------------------------------------------
**I hope my suggestions could be helpful and we can improve this outstanding project! :smiley: 
Happy coding! :1st_place_medal: :wave: :clinking_glasses:**

**Comment by mpa-mxiang** [comment]
Thank you so much, solved and now I will close this issue.
